# Generated by Django 4.2.6 on 2023-12-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_item_alter_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
